name: Laravel CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: laravel_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v3

      # 2. Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql
          ini-values: post_max_size=256M, max_execution_time=300

      # 3. Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      # 4. Copy .env example to .env
      - name: Copy .env example to .env
        run: cp .env.example .env

      # 5. Generate application key
      - name: Generate application key
        run: php artisan key:generate

      # 6. Set up database
      - name: Set up database
        run: php artisan migrate --force

      # 7. Set up Node.js (required for Tailwind CSS)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 8. Install NPM dependencies
      - name: Install NPM dependencies
        run: npm install

      # 9. Build frontend assets (Tailwind CSS)
      - name: Build Tailwind CSS
        run: npm run build

      # 10. Run Laravel tests
      - name: Run tests
        run: php artisan test

      # 11. Package artifacts into a ZIP file
      - name: Package artifacts
        run: zip -r application.zip . -x "node_modules/*" "vendor/*" ".git/*"

      # 12. Upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: application-artifact
          path: application.zip

      # 13. Deploy the application
      - name: Deploy application
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t my-laravel-app .
          docker run -d -p 80:80 --name laravel-app my-laravel-app
