name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Clona el repositorio
    - name: Checkout Code
      uses: actions/checkout@v3

    # Configura PHP y Composer
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo_mysql
        coverage: none

    # Configura Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Construcción de la imagen Docker
    - name: Build Docker Image
      run: |
        docker build -t laravel-node-app .

    # Prueba del contenedor Docker
    - name: Run Docker Container
      run: |
        docker run -d -p 8080:9000 --name test-container laravel-node-app
        sleep 10 # Tiempo para inicializar el contenedor
        curl -I http://localhost:8080

    # Eliminar contenedor de prueba
    - name: Cleanup Docker Container
      run: |
        docker stop test-container
        docker rm test-container
